# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='label',
            new_name='description',
        ),
        migrations.AddField(
            model_name='map',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='map',
            name='rotation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='x_extent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='x_mesh_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='x_origin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='y_extent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='y_mesh_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='y_origin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
