# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170825_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='rotation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='x_extent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='x_mesh_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='x_origin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='y_extent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='y_mesh_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='y_origin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='z',
            field=models.FloatField(),
        ),
    ]
